### ISSUE TITLE
Image Optimization, suggestion

### ISSUE THREAD

**Issue by GrassyAirplane** [AoTTG-2/Aottg2-Website#1]
My wifi is bad but it took ~50 seconds to fully load 
![Capture](https://github.com/user-attachments/assets/6eb86628-6f83-45ec-98c6-db19843addb6)

**Comment by gisketch** [comment]
merged but it'll take a while before it'd be deployed/published as we don't have an auto deployment set up currently. would have to manually change. thanks!!
